# codecov yaml
comment: yes # do not comment PR with the result
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no  # if true: only post the comment if coverage changes
  require_base: yes    # [yes :: must have a base report to post]
  require_head: yes    # [yes :: must have a head report to post]

coverage:
  range: 70..100 

  status:
    project: # settings affecting project coverage
      default:
        enabled: yes
        target: 70% # auto % coverage target
        threshold: 5%  # we allow here 100% change to unblock PRs (will be set later)

    patch:
      default:
        enabled: yes
        target: 70% # auto % coverage target
        threshold: 5%  # we allow here 100% change to unblock PRs (will be set later)
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes
