site_name: iceoryx.io
site_url: https://iceoryx.io
repo_url: https://github.com/eclipse/iceoryx
docs_dir: doc/website/
remote_branch: main
markdown_extensions:
  - markdown_include.include:
      base_path: doc
  - admonition
plugins:
  - awesome-pages
  - search
theme:
  name: 'material'
  font: false # don't load fonts from Google due to GDPR
  palette:
    primary: light blue
  copyright: Copyright &copy; 2020 Eclipse Foundation
