@startuml

skinparam classAttributeIconSize 0

enum ActiveChunk {
  FIRST
  SECOND
}

class Transaction {
  +activeChunk: ActiveChunk
  +abaCounter: uint32_t
}

class StatusPortData {
  +latestTransaction: std::atomic<Transaction>
  +serviceDescription: capro::ServiceDescription
  +chunks: SharedChunk[2]
}

class StatusPortReader<T> {
  +StatusPortReader(statusPortDataPtr: cxx::not_null<StatusPortData* const)
  +take(callable: cxx::function_ref<void(const T&)>): void
  -getMembers() const: const StatusPortData*
  -getMembers(): StatusPortData*
  -m_copyOfUserData: T
  -m_statusPortDataPtr: StatusPortData*
}


class StatusPortWriter<T> {
  +StatusPortWriter(statusPortDataPtr: cxx::not_null<StatusPortData* const)
  +store(callable: cxx::function_ref<void(T&)>): void
  -getMembers() const: const StatusPortData*
  -getMembers(): StatusPortData*
  -m_statusPortDataPtr: StatusPortData*
}

StatusPortWriter ..> StatusPortData
StatusPortReader ..> StatusPortData

@enduml
